application: first-project-1062
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: .*
  script: Stage4Intro.app
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest